[Distribution]
Distribution=opensuse
Release=tumbleweed

[Output]
OutputDirectory=mkosi.output
Format=none
ImageVersion=0.0

[Content]
SELinuxRelabel=true
Packages=
 Kalpa-release
 Kalpa-release-appliance
 gcc
 gdb
 git
 k3s-selinux
 ltrace
 netcat-openbsd
 make
 pandoc
 patch
 strace
 traceroute
