[Config]
Dependencies=base

[Match]
Architecture=|x86-64
Architecture=|arm64

[Output]
Format=sysext
Overlay=yes
ImageId=rke2
Output=%i-%v.%a
ManifestFormat=json

[Validation]
Verity=no

[Content]
SELinuxRelabel=true
CleanPackageMetadata=yes
BaseTrees=%O/base
Packages= 
  rke2 
  rke2-selinux

[Build]
Environment=SYSTEMD_REPART_OVERRIDE_FSTYPE_ROOT=squashfs
Environment=SYSEXT_SCOPE=system
