[Config]
Dependencies=git

[Output]
Format=sysext
Overlay=yes
ImageId=packaging
Output=%i-%v.%a
ManifestFormat=json

[Validation]
Verity=no

[Content]
CleanPackageMetadata=yes
BaseTrees=%O/base
Packages=osc build vim vim-data cnf cnf-bash cargo-vendor-filterer obs-service-download_files obs-service-tar obs-service-tar_scm obs-service-obs_scm obs-service-set_version obs-service-recompress obs-service-go_modules obs-service-cargo obs-service-product_converter obs-service-format_spec_file osc-plugin-cycle osc-plugin-origin osc-plugin-staging patterns-devel-osc-devel_osc_build quilt spec-cleaner-format_spec_file starship -obs-service-format_spec_file rust+cargo obs-service-cargo obs-service-download_files obs-service-go_modules obs-service-recompress obs-service-set_version obs-scm-bridge python3-py2pack /usr/bin/xsltproc python3-kiwi qemu-arm qemu-linux-user

[Build]
Environment=SYSTEMD_REPART_OVERRIDE_FSTYPE_ROOT=squashfs
Environment=SYSEXT_SCOPE=system
